### ISSUE TITLE
测试restful API所遇到的一些问题

### ISSUE THREAD

**Issue by hahajiansheng** [alibaba/nginx-tfs#13]
1.在post数据的时候如果不加suffix=这个参数会提示400错误，然后加了之后就可以提交数据了，然后我多加了个simple_name参数就又报400错误，然后看你api说明的时候这两个不加的时候也应该是可以的，加了两个也可以，现在这个算是bug吗？
2.我用post提交完数据之后返回文件名了，然后用这个文件名想用restful api的get接口搞下来，但始终无效，报404 not found，然后用后台的nameserver查看那个文件名发现是已经提交上去了的，请问这是什么原因？

**Comment by zhcn381** [comment]
@hahajiansheng 你好，麻烦把你的完整的post和get的url都给我看看，使用curl来完成这两种功能的用法是这样的：
curl --data-binary @file_to_up ngx_host:port/v1/tfs
curl ngx_host:port/v1/tfs/T1pFETByCT1RCvBVdK -o dw.file
